# frozen_string_literal: true

require "yaml"
require_relative "../handler"
require_relative "go_module_parser"
require_relative "../registry"

# GoDepResolver handler - second-pass resolver that patches dependsOn relations
# onto ApplicationComponents generated by GoGrapher.
#
# Runs after all GoGraphers complete (iteration 2 of the executor loop) so the
# database contains the full set of freshly-generated ApplicationComponents.
# Output goes to a single shared generated/relationships.yaml file (all repos
# combined), loaded after modules.yaml alphabetically so its version of each
# component — with dependsOn — takes precedence.
#
# One Import:GoDepResolver:* resource is emitted by each GoGrapher run; this
# handler is registered as a child of GoGrapher via the generates relation so
# the executor knows to wait until GoGrapher has completed.
#
# Configuration:
#   import/config/path - Path to the Go repository root (same as GoGrapher)
class Archsight::Import::Handlers::GoDepResolver < Archsight::Import::Handler
  include Archsight::Import::Handlers::GoModuleParser

  def execute
    @path = config("path")
    raise "Missing required config: path" unless @path
    raise "Directory not found: #{@path}" unless File.directory?(@path)

    import_resource.annotations["import/outputPath"] ||= "generated/relationships.yaml"

    modules = discover_modules(@path)
    return write_yaml(YAML.dump(self_marker)) if modules.empty?

    existing_components = database&.instances_by_kind("ApplicationComponent") || {}
    output = +""

    modules.each do |rel_dir, mod_name|
      mod_dir = rel_dir == "." ? @path : File.join(@path, rel_dir)
      dep_names = compute_deps(mod_dir, mod_name, existing_components)
      next if dep_names.empty?

      comp_name = component_name(mod_name)
      existing = existing_components[comp_name]
      next unless existing

      # Rebuild the full ApplicationComponent merging dependsOn into the existing
      # spec (which carries realizedThrough, exposes, etc. from GoGrapher).
      spec = existing.raw.fetch("spec", {}).dup
      spec["dependsOn"] = { "applicationComponents" => dep_names }

      component = {
        "apiVersion" => "architecture/v1alpha1",
        "kind" => "ApplicationComponent",
        "metadata" => {
          "name" => comp_name,
          "annotations" => existing.annotations.merge(
            "generated/script" => import_resource.name,
            "generated/at" => Time.now.utc.iso8601
          )
        },
        "spec" => spec
      }
      output << YAML.dump(component)
    end

    write_yaml(output + YAML.dump(self_marker))
  end

  private

  def compute_deps(mod_dir, mod_name, existing_components)
    prefix = same_origin_prefix(mod_name)
    return [] unless prefix

    go_mod_requires(mod_dir)
      .select { |r| r.start_with?(prefix) && r != mod_name }
      .filter_map { |r| component_name(r) if existing_components.key?(component_name(r)) }
      .sort.uniq
  end
end

Archsight::Import::Registry.register("go-dep-resolver", Archsight::Import::Handlers::GoDepResolver)
