# frozen_string_literal: true

require "bundler/gem_tasks"

# Override release tasks to skip git operations in CI
if ENV["CI"]
  Rake::Task["release:guard_clean"].clear
  Rake::Task["release:source_control_push"].clear
end

require "minitest/test_task"

Minitest::TestTask.create do |t|
  # Ensure test_helper is loaded first for proper SimpleCov initialization
  t.test_prelude = 'require "test_helper"'
end

# Clean coverage folder before running tests to ensure accurate results
desc "Clean coverage folder"
task :clean_coverage do
  require "fileutils"
  FileUtils.rm_rf("coverage")
end

Rake::Task["test"].enhance([:clean_coverage])

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "steep/rake_task"

Steep::RakeTask.new do |t|
  t.check.severity_level = :error
  t.watch.verbose
end

task default: %i[test steep rubocop]

require "bundler/audit/task"
Bundler::Audit::Task.new

desc "Update lib/archsight/version.rb from git tag"
task :version do
  tag = `git describe --tags --abbrev=0 2>/dev/null`.strip
  abort "No valid version tag found (expected v*.*.* format)" unless tag.match?(/^v\d+\.\d+/)

  version = tag.delete_prefix("v")
  version_file = File.expand_path("lib/archsight/version.rb", __dir__)
  content = <<~RUBY
    # frozen_string_literal: true

    # This file is automatically generated by `rake version` from git tags.
    # Do not edit manually.

    module Archsight
      VERSION = "#{version}"
    end
  RUBY
  File.write(version_file, content)
  puts "Updated version.rb to #{version}"
end
