# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "steep/rake_task"

Steep::RakeTask.new do |t|
  t.check.severity_level = :error
  t.watch.verbose
end

task default: %i[test steep rubocop]

require "bundler/audit/task"
Bundler::Audit::Task.new

desc "Update lib/archsight/version.rb from git tag"
task :version do
  tag = `git describe --tags --abbrev=0 2>/dev/null`.strip
  abort "No valid version tag found (expected v*.*.* format)" unless tag.match?(/^v\d+\.\d+/)

  version = tag.delete_prefix("v")
  version_file = File.expand_path("lib/archsight/version.rb", __dir__)
  content = <<~RUBY
    # frozen_string_literal: true

    # This file is automatically generated by `rake version` from git tags.
    # Do not edit manually.

    module Archsight
      VERSION = "#{version}"
    end
  RUBY
  File.write(version_file, content)
  puts "Updated version.rb to #{version}"
end
