---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:API:archsight
spec:
  generates:
    dataObjects:
    - Archsight:Kind
    - Archsight:Instance
    - Archsight:Filter
    - Archsight:Analysis
    - Archsight:AnalysisSection
    - Archsight:EditorField
    - Archsight:RelationOption
    - Archsight:Generate
    - Archsight:Save
    - Archsight:PageTree
    - Archsight:PageTreeNode
    - Archsight:PageTag
    - Archsight:PageLink
    - Archsight:Page
    - Archsight:PageTocEntry
    - Archsight:EmailRecipient
    applicationInterfaces:
    - Public:Archsight:v1:RestAPI
