---
apiVersion: architecture/v1alpha1
kind: TechnologyArtifact
metadata:
  name: Repo:ionos-cloud:archsight
  annotations:
    architecture/ruby/modules: |
      digraph G {
       "rankdir" = "LR";
       "compound" = "true";
       "splines" = "curved";
       "concentrate" = "true";
       "ranksep" = "0.6";
       "nodesep" = "0.15";
       "fontname" = "Helvetica";
       "fontsize" = "10";
        node [ "fontname" = "Helvetica" "fontsize" = "8" "shape" = "box" "style" = "rounded,filled" "fillcolor" = "white" "height" = "0.2" "width" = "0.4" ];
        edge [ "fontname" = "Helvetica" "fontsize" = "8" ];
        subgraph "cluster_archsight" {
       "label" = "archsight";
       "style" = "rounded,filled";
       "fillcolor" = "#ddeeff";
       "fontname" = "Helvetica Bold";
       "fontsize" = "13";
        "archsight" [ "label" = "" "style" = "invis" "width" = "0" "height" = "0" ];
        "analysis" [ "label" = "analysis" ];
        "annotations" [ "label" = "annotations" ];
        "cli" [ "label" = "cli" ];
        "configuration" [ "label" = "configuration" ];
        "database" [ "label" = "database" ];
        "documentation" [ "label" = "documentation" ];
        "editor" [ "label" = "editor" ];
        "graph" [ "label" = "graph" ];
        "helpers" [ "label" = "helpers" ];
        "import" [ "label" = "import" ];
        "linter" [ "label" = "linter" ];
        "mcp" [ "label" = "mcp" ];
        "query" [ "label" = "query" ];
        "renderer" [ "label" = "renderer" ];
        "resources" [ "label" = "resources" ];
        "template" [ "label" = "template" ];
        "version" [ "label" = "version" ];
        "web" [ "label" = "web" ];
        }
        "cli" -> "analysis" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "database" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "helpers" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "import" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "linter" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "resources" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "template" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "web" [ "color" = "#cc8800" "style" = "solid" ];
        "mcp" -> "analysis" [ "color" = "#2a8a1e" "style" = "solid" ];
        "web" -> "analysis" [ "color" = "#995500" "style" = "solid" ];
      }
    generated/script: Import:RubyGrapher:ionos-cloud:archsight
    generated/at: '2026-07-02T11:39:01Z'
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:RubyGrapher:ionos-cloud:archsight
  annotations:
    generated/at: '2026-07-02T11:39:01Z'
    generated/configHash: d8007a10df1f8672
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:RubyGrapher:ionos-cloud:archsight
spec:
  generates:
    technologyArtifacts:
    - Repo:ionos-cloud:archsight
