---
apiVersion: architecture/v1alpha1
kind: TechnologyArtifact
metadata:
  name: Repo:ionos-cloud:archsight
  annotations:
    architecture/javascript/modules: |
      digraph G {
       "rankdir" = "LR";
       "compound" = "true";
       "splines" = "curved";
       "concentrate" = "true";
       "ranksep" = "0.6";
       "nodesep" = "0.15";
       "fontname" = "Helvetica";
       "fontsize" = "10";
        node [ "fontname" = "Helvetica" "fontsize" = "8" "shape" = "box" "style" = "rounded,filled" "fillcolor" = "white" "height" = "0.2" "width" = "0.4" ];
        edge [ "fontname" = "Helvetica" "fontsize" = "8" ];
        subgraph "cluster_frontend" {
       "label" = "frontend";
       "style" = "rounded,filled";
       "fillcolor" = "#ddeeff";
       "fontname" = "Helvetica Bold";
       "fontsize" = "13";
        "frontend" [ "label" = "" "style" = "invis" "width" = "0" "height" = "0" ];
        "api" [ "label" = "api" ];
        "composables" [ "label" = "composables" ];
        "router" [ "label" = "router" ];
        }
        "composables" -> "css" [ "color" = "#2a8a1e" "style" = "solid" ];
        "router" -> "components" [ "color" = "#cc8800" "style" = "solid" ];
      }
    generated/script: Import:JavascriptGrapher:ionos-cloud:archsight
    generated/at: '2026-09-30T15:04:39Z'
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:JavascriptGrapher:ionos-cloud:archsight
  annotations:
    generated/at: '2026-09-30T15:04:39Z'
    generated/configHash: 9e4ae8bf377c6c55
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:JavascriptGrapher:ionos-cloud:archsight
spec:
  generates:
    technologyArtifacts:
    - Repo:ionos-cloud:archsight
---
apiVersion: architecture/v1alpha1
kind: TechnologyArtifact
metadata:
  name: Repo:ionos-cloud:archsight
  annotations:
    architecture/ruby/modules: |
      digraph G {
       "rankdir" = "LR";
       "compound" = "true";
       "splines" = "curved";
       "concentrate" = "true";
       "ranksep" = "0.6";
       "nodesep" = "0.15";
       "fontname" = "Helvetica";
       "fontsize" = "10";
        node [ "fontname" = "Helvetica" "fontsize" = "8" "shape" = "box" "style" = "rounded,filled" "fillcolor" = "white" "height" = "0.2" "width" = "0.4" ];
        edge [ "fontname" = "Helvetica" "fontsize" = "8" ];
        subgraph "cluster_archsight" {
       "label" = "archsight";
       "style" = "rounded,filled";
       "fillcolor" = "#ddeeff";
       "fontname" = "Helvetica Bold";
       "fontsize" = "13";
        "archsight" [ "label" = "" "style" = "invis" "width" = "0" "height" = "0" ];
        "analysis" [ "label" = "analysis" ];
        "annotations" [ "label" = "annotations" ];
        "cli" [ "label" = "cli" ];
        "configuration" [ "label" = "configuration" ];
        "database" [ "label" = "database" ];
        "diagram" [ "label" = "diagram" ];
        "documentation" [ "label" = "documentation" ];
        "editor" [ "label" = "editor" ];
        "graph" [ "label" = "graph" ];
        "helpers" [ "label" = "helpers" ];
        "import" [ "label" = "import" ];
        "linter" [ "label" = "linter" ];
        "mcp" [ "label" = "mcp" ];
        "page_loader" [ "label" = "page_loader" ];
        "page_tree" [ "label" = "page_tree" ];
        "query" [ "label" = "query" ];
        "renderer" [ "label" = "renderer" ];
        "resources" [ "label" = "resources" ];
        "template" [ "label" = "template" ];
        "version" [ "label" = "version" ];
        "web" [ "label" = "web" ];
        }
        "analysis" -> "annotations" [ "color" = "#2266cc" "style" = "solid" ];
        "annotations" -> "query" [ "color" = "#2a8a1e" "style" = "solid" ];
        "cli" -> "analysis" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "database" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "diagram" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "helpers" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "import" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "linter" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "resources" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "template" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "version" [ "color" = "#cc8800" "style" = "solid" ];
        "cli" -> "web" [ "color" = "#cc8800" "style" = "solid" ];
        "database" -> "graph" [ "color" = "#8822cc" "style" = "solid" ];
        "database" -> "page_loader" [ "color" = "#8822cc" "style" = "solid" ];
        "database" -> "query" [ "color" = "#8822cc" "style" = "solid" ];
        "database" -> "resources" [ "color" = "#8822cc" "style" = "solid" ];
        "documentation" -> "resources" [ "color" = "#228888" "style" = "solid" ];
        "documentation" -> "template" [ "color" = "#228888" "style" = "solid" ];
        "editor" -> "database" [ "color" = "#995500" "style" = "solid" ];
        "editor" -> "page_loader" [ "color" = "#995500" "style" = "solid" ];
        "editor" -> "resources" [ "color" = "#995500" "style" = "solid" ];
        "linter" -> "helpers" [ "color" = "#2a8a1e" "style" = "solid" ];
        "mcp" -> "analysis" [ "color" = "#cc8800" "style" = "solid" ];
        "mcp" -> "database" [ "color" = "#cc8800" "style" = "solid" ];
        "mcp" -> "resources" [ "color" = "#cc8800" "style" = "solid" ];
        "resources" -> "annotations" [ "color" = "#995500" "style" = "solid" ];
        "resources" -> "helpers" [ "color" = "#995500" "style" = "solid" ];
        "template" -> "resources" [ "color" = "#4444aa" "style" = "solid" ];
        "web" -> "analysis" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "database" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "documentation" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "editor" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "graph" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "helpers" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "mcp" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "page_tree" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "query" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "renderer" [ "color" = "#2266cc" "style" = "solid" ];
        "web" -> "resources" [ "color" = "#2266cc" "style" = "solid" ];
      }
    generated/script: Import:RubyGrapher:ionos-cloud:archsight
    generated/at: '2026-09-30T15:04:39Z'
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:RubyGrapher:ionos-cloud:archsight
  annotations:
    generated/at: '2026-09-30T15:04:39Z'
    generated/configHash: d8007a10df1f8672
spec: {}
---
apiVersion: architecture/v1alpha1
kind: Import
metadata:
  name: Import:RubyGrapher:ionos-cloud:archsight
spec:
  generates:
    technologyArtifacts:
    - Repo:ionos-cloud:archsight
