module Archsight
  VERSION: String

  class Error < StandardError
  end

  def self.configuration: () -> Configuration
  def self.configure: () { (Configuration) -> void } -> void
  def self.resources_dir: () -> String
  def self.resources_dir=: (String) -> String
  def self.reset_configuration!: () -> Configuration

  module Helpers
    def self.deep_merge: (Hash[untyped, untyped], Hash[untyped, untyped]) -> Hash[untyped, untyped]
  end
end
