# frozen_string_literal: true

# Generated module adds annotations for tracking generated resources
module Archsight::Annotations::Generated
  def self.included(base)
    base.class_eval do
      annotation "generated/script",
                 description: "Name of the script that generated this resource",
                 title: "Generated By",
                 sidebar: false
      annotation "generated/at",
                 description: "Timestamp when this resource was generated (ISO8601)",
                 title: "Generated At",
                 sidebar: false
    end
  end
end
