# frozen_string_literal: true

require "test_helper"
require "tmpdir"
require "fileutils"
require "archsight/database"
require "archsight/export"
require "archsight/export/confluence/exporter"
require_relative "fake_confluence"
require_relative "fake_drawio_cli"

class ConfluenceExporterTest < Minitest::Test
  include FakeDrawioCli

  TOKEN = "secret-token"
  URL = "https://wiki.example.com/spaces/SP/pages/42/Test"

  def setup
    @dir = Dir.mktmpdir
    FileUtils.mkdir_p(File.join(@dir, "pages"))
    File.binwrite(File.join(@dir, "pages/a.png"), "\x89PNG fake")
    write_page("guide", "# Guide\n\nHello ![Pic](a.png)\n", confluence: URL)
    write_page("nolink", "text\n")
    @fake = FakeConfluence.new(token: TOKEN)
    @fake.add_page(42)
  end

  def teardown
    FileUtils.rm_rf(@dir)
  end

  def write_page(name, body, confluence: nil)
    front = ["title: #{name.capitalize}", ("confluence: #{confluence}" if confluence)].compact.join("\n")
    File.write(File.join(@dir, "pages/#{name}.md"), "---\n#{front}\n---\n\n#{body}")
  end

  def exporter(settings_drawio: false, **)
    db = Archsight::Database.new(@dir, compute_annotations: false).tap(&:reload!)
    secret = Archsight::Export::Confluence::Credentials::Secret.new(TOKEN)
    settings = Archsight::Export::Confluence::Credentials::Settings.new(token: secret, drawio: settings_drawio)
    Archsight::Export::Confluence::Exporter.new(
      database: db, resources_dir: @dir, settings: settings,
      client_factory: ->(base, token) { Archsight::Export::Confluence::Client.new(base: base, token: token, transport: @fake) }, **
    )
  end

  def run_export(names = ["guide"], **)
    exporter(**).run(names)
  end

  def test_a_page_never_exported_is_blocked_and_reported_as_not_exported
    result = run_export.first

    assert_equal :blocked, result.status
    assert_includes result.message, "not exported by Archsight before"
    assert_includes result.message, "--force"
    assert_equal "<p>hello</p>", @fake.pages["42"].body, "nothing was written"
    assert_empty @fake.uploads
  end

  def test_force_exports_the_first_time_and_leaves_marker_message_attachment_and_lock
    result = run_export(force: true).first
    page = @fake.pages["42"]

    assert_equal :exported, result.status
    assert_includes result.message, "version 2"
    assert_includes result.message, "locked for other editors"
    assert_includes page.body, "generated by Archsight from <code>pages/guide.md</code>"
    assert_includes page.body, '<ri:attachment ri:filename="a.png" />'
    refute_includes page.body, "<h1>Guide</h1>", "the title repeated by the first heading is dropped"
    assert_equal "Test", page.title, "the Confluence title is kept"
    assert_match(%r{\AGenerated by Archsight .+ from pages/guide\.md, do not edit in Confluence; replaced the content that was there\z}, page.properties[:message])
    assert_equal 2, page.properties["archsight"][:value]["version"]
    assert_equal ["a.png"], page.attachments.keys
    assert_equal [{ "operation" => "update", "restrictions" => { "user" => [{ "type" => "known", "username" => "exporter" }] } }], page.restriction
  end

  def test_a_second_run_changes_nothing
    run_export(force: true)
    @fake.requests.clear
    result = run_export.first

    assert_equal :unchanged, result.status
    refute(@fake.requests.any? { |r| %w[PUT POST].include?(r[:verb]) }, "no write when nothing changed")
    assert_equal 2, @fake.pages["42"].version
  end

  def test_a_changed_source_is_exported_again_and_only_changed_attachments_upload
    run_export(force: true)
    @fake.uploads.clear
    write_page("guide", "# Guide\n\nHello again ![Pic](a.png)\n", confluence: URL)
    result = run_export.first

    assert_equal :exported, result.status
    assert_includes result.message, "version 3"
    assert_empty @fake.uploads, "the image did not change"
    assert_includes @fake.pages["42"].body, "Hello again"
  end

  def test_a_page_edited_in_confluence_is_blocked_with_who_and_when_and_not_written
    run_export(force: true)
    @fake.edit(42, by: "Alice Example")
    result = run_export.first

    assert_equal :blocked, result.status
    assert_includes result.message, "modified in Confluence by Alice Example at 2026-02-02T12:00:00.000Z"
    assert_includes result.message, "version 3, last exported 2"
    assert_equal "<p>edited</p>", @fake.pages["42"].body
  end

  def test_force_overwrites_an_edited_page_and_says_so_in_the_revision
    run_export(force: true)
    @fake.edit(42, by: "Alice Example")
    result = run_export(force: true).first

    assert_equal :exported, result.status
    assert_includes @fake.pages["42"].properties[:message], "overwrote the changes of versions 3..3"
    assert_includes @fake.pages["42"].body, "generated by Archsight"
    assert_equal :unchanged, run_export.first.status, "managed again after the forced export"
  end

  def test_a_refused_lock_does_not_fail_the_export
    @fake.restriction_error = "You are not permitted to set restrictions"
    result = run_export(force: true).first

    assert_equal :exported, result.status
    assert_includes result.message, "NOT locked"
    assert_includes result.message, "not permitted"
  end

  def test_no_lock_skips_the_restriction
    run_export(force: true, lock: false)

    assert_nil @fake.pages["42"].restriction
  end

  def test_dry_run_writes_nothing
    @fake.requests.clear
    result = run_export(force: true, dry_run: true).first

    assert_equal :would_export, result.status
    refute(@fake.requests.any? { |r| %w[PUT POST].include?(r[:verb]) })
    assert_empty @fake.uploads
  end

  def test_pages_without_a_link_unknown_names_and_all_mode
    assert_equal :skipped, run_export(["nolink"]).first.status
    assert_equal [:failed], run_export(["nope"]).map(&:status)
    assert_equal ["guide"], run_export([], force: true).map(&:page), "without names only linked pages are exported"
  end

  def test_a_page_with_a_broken_image_is_not_exported
    write_page("guide", "![x](missing.png)\n", confluence: URL)
    result = run_export(force: true).first

    assert_equal :failed, result.status
    assert_includes result.message, "no such file"
    assert_equal "<p>hello</p>", @fake.pages["42"].body
  end

  def test_a_display_url_is_resolved_by_title
    write_page("guide", "x\n", confluence: "https://wiki.example.com/display/SP/Test")

    assert_equal :exported, run_export(force: true).first.status
  end

  def test_the_token_is_only_sent_as_bearer_header_and_never_shows_up_in_results_or_paths
    results = run_export(force: true)

    refute_includes results.map(&:message).join, TOKEN
    refute(@fake.requests.any? { |r| r[:path].include?(TOKEN) })
  end

  def test_a_rejected_token_is_a_clear_failure
    @fake = FakeConfluence.new(token: "other")
    result = run_export(force: true).first

    assert_equal :failed, result.status
    assert_includes result.message, "401"
    refute_includes result.message, TOKEN
  end

  def test_the_drawio_setting_decides_whether_diagrams_become_macros_and_the_flag_overrides_it
    FileUtils.cp(File.join(__dir__, "../diagram/fixtures/dag.asd"), File.join(@dir, "pages/flow.asd"))
    write_page("guide", "![Flow](flow.asd)\n", confluence: URL)

    with_fake_drawio_cli do
      run_export(force: true, settings_drawio: true)

      assert_includes @fake.pages["42"].body, 'ac:name="drawio"'
      assert_includes @fake.pages["42"].attachments.keys, "flow.png"

      run_export(force: true, settings_drawio: true, drawio: false)

      refute_includes @fake.pages["42"].body, 'ac:name="drawio"'
      assert_includes @fake.pages["42"].body, "<ac:image>"

      run_export(force: true, settings_drawio: false, drawio: true)

      assert_includes @fake.pages["42"].body, 'ac:name="drawio"'
    end
  end

  def test_attachments_an_earlier_export_added_and_the_page_no_longer_uses_are_removed_but_foreign_ones_stay
    run_export(force: true)
    @fake.pages["42"].attachments["colleague.pdf"] = { id: "999" }
    write_page("guide", "no image any more\n", confluence: URL)
    run_export

    assert_equal ["colleague.pdf"], @fake.pages["42"].attachments.keys
    assert_equal 1, @fake.deleted.length
  end
end
