# frozen_string_literal: true

require "test_helper"
require "tmpdir"
require "fileutils"
require "base64"
require "rexml/document"
require "archsight/database"
require "archsight/helpers"
require "archsight/export"
require "archsight/export/confluence/storage"
require_relative "fake_drawio_cli"

class ConfluenceStorageTest < Minitest::Test
  include FakeDrawioCli

  Storage = Archsight::Export::Confluence::Storage

  def setup
    @dir = Dir.mktmpdir
    FileUtils.mkdir_p(File.join(@dir, "pages/img"))
    File.binwrite(File.join(@dir, "pages/img/a.png"), "\x89PNG fake")
    File.write(File.join(@dir, "pages/flow.asd"), %(component "a" { label "Hello" }\n))
    File.write(File.join(@dir, "pages/other.md"), "---\ntitle: Other Page\nconfluence: https://wiki.example.com/spaces/SP/pages/55/Other\n---\n\nx\n")
    File.write(File.join(@dir, "pages/plain.md"), "---\ntitle: Plain Page\n---\n\nx\n")
    @db = Archsight::Database.new(@dir, compute_annotations: false).tap(&:reload!)
  end

  def teardown
    FileUtils.rm_rf(@dir)
  end

  def convert(markdown, toc: false, drawio: false)
    storage = Storage.new(page_name: "p", source: "pages/p.md", base_dir: "pages", resources_dir: @dir,
                          wiki: Archsight::Helpers::WikiLinks.new(@db), page_id: "1", base: "https://wiki.example.com", drawio: drawio,
                          diagram_links: Archsight::Export::Confluence::DiagramLinks.new(@db))
    storage.convert(markdown, toc: toc)
  end

  def well_formed!(body)
    REXML::Document.new(%(<root xmlns:ac="a" xmlns:ri="r">#{body}</root>))
  rescue REXML::ParseException => e
    flunk "not well-formed storage XML: #{e.message}\n#{body}"
  end

  def test_banner_says_the_page_is_generated_and_names_the_source
    body = convert("hi\n").body

    assert_includes body, 'ac:name="info"'
    assert_includes body, "generated by Archsight from <code>pages/p.md</code>"
    assert_includes body, "edit the source instead"
  end

  def test_headings_tables_lists_and_text_escaping
    result = convert("# Title\n\n| A | B |\n|---|---|\n| 1 < 2 | x & y |\n\n- one\n- two\n\nSome *emphasis* and `code`.\n")
    well_formed!(result.body)

    assert_includes result.body, "<h1>Title</h1>"
    assert_includes result.body, "<td>1 &lt; 2</td>"
    assert_includes result.body, "<td>x &amp; y</td>"
    assert_includes result.body, "<li>one</li>"
    assert_includes result.body, "<em>emphasis</em>"
  end

  def test_toc_macro_only_when_asked
    refute_includes convert("# A\n").body, 'ac:name="toc"'
    assert_includes convert("# A\n", toc: true).body, 'ac:name="toc"'
  end

  def test_code_blocks_become_code_macros_with_a_known_language
    body = convert("```ruby\nputs 1 ]]> 2\n```\n\n```go\nx\n```\n\n```json\n{}\n```\n").body
    well_formed!(body)

    assert_includes body, '<ac:parameter ac:name="language">ruby</ac:parameter>'
    assert_includes body, '<ac:parameter ac:name="language">text</ac:parameter>'
    assert_includes body, '<ac:parameter ac:name="language">javascript</ac:parameter>'
    assert_includes body, "puts 1 ]]]]><![CDATA[> 2"
  end

  def test_wiki_links_point_to_the_confluence_page_when_it_has_one
    body = convert("See [[other]] and [[Plain Page]] and [[Other Page|the label]] and [[ApplicationComponent/Nope]].\n").body
    well_formed!(body)

    assert_includes body, '<a href="https://wiki.example.com/pages/viewpage.action?pageId=55">Other Page</a>'
    assert_includes body, "and Plain Page and"
    assert_includes body, '<a href="https://wiki.example.com/pages/viewpage.action?pageId=55">the label</a>'
    assert_includes body, "and ApplicationComponent/Nope."
    refute_includes body, "ARCHSIGHT"
  end

  def test_embeds_and_links_in_code_are_left_alone
    body = convert("![[View/Services]]\n\n`[[other]]` and `![[View/X]]`\n").body

    assert_includes body, "<em>View/Services (live content, shown in Archsight only)</em>"
    assert_includes body, "<code>[[other]]</code>"
    refute_includes body, "ARCHSIGHT"
  end

  def test_an_image_is_attached_and_referenced
    result = convert("![Photo](img/a.png)\n")

    assert_includes result.body, '<ac:image ac:alt="Photo"><ri:attachment ri:filename="a.png" /></ac:image>'
    assert_equal ["a.png"], result.attachments.keys
    assert_equal "image/png", result.attachments["a.png"].content_type
    assert_equal "\x89PNG fake".b, result.attachments["a.png"].data.b
  end

  def test_external_images_stay_urls
    assert_includes convert("![x](https://example.com/a.png)\n").body, '<ri:url ri:value="https://example.com/a.png" />'
  end

  def test_asd_blocks_and_files_become_diagram_images_without_drawio
    fenced = convert("```asd\ncomponent \"a\" { label \"Hello\" }\n```\n")
    file = convert("![Flow](flow.asd)\n")

    assert_empty fenced.problems
    assert_includes fenced.attachments.keys, "p-diagram-1.svg"
    assert_match(%r{<ac:image><ri:attachment ri:filename="p-diagram-1\.(png|svg)" /></ac:image>}, fenced.body)
    assert_includes file.attachments.keys, "flow.svg"
    assert_match(/ri:filename="flow\.(png|svg)"/, file.body)
    refute_includes file.body, 'ac:name="drawio"'
    well_formed!(fenced.body + file.body)
  end

  def test_asd_goes_through_drawio_as_a_wrapped_svg_when_the_confluence_has_it
    with_fake_drawio_cli do
      result = convert("![Flow](flow.asd)\n\n```asd\ncomponent \"b\" { }\n```\n", drawio: true)
      well_formed!(result.body)

      assert_empty result.problems
      assert_equal 2, result.body.scan('ac:name="drawio"').length
      assert_includes result.body, '<ac:parameter ac:name="diagramName">flow</ac:parameter>'
      assert_includes result.body, '<ac:parameter ac:name="diagramName">p-diagram-1</ac:parameter>'
      assert_equal %w[flow flow.png p-diagram-1 p-diagram-1.png], result.attachments.keys.sort
      xml = result.attachments["flow"].data
      well_formed!(xml)

      assert_includes xml, "shape=image"
      assert_includes xml, "image=data:image/svg+xml,"
      assert_equal "application/vnd.jgraph.mxfile", result.attachments["flow"].content_type
    end
  end

  def test_svg_files_are_drawio_only_when_the_confluence_has_it
    File.write(File.join(@dir, "pages/logo.svg"), '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="20"><rect width="10" height="20"/></svg>')
    with_fake_drawio_cli do
      plain = convert("![Logo](logo.svg)\n")
      native = convert("![Logo](logo.svg)\n", drawio: true)

      refute_includes plain.body, "drawio"
      assert_equal ["logo.svg"], plain.attachments.keys
      assert_includes native.body, '<ac:parameter ac:name="diagramName">logo</ac:parameter>'
      assert_includes native.attachments["logo"].data, 'pageWidth="10" pageHeight="20"'
    end
  end

  def test_drawio_files_are_images_when_the_confluence_does_not_have_the_app
    File.write(File.join(@dir, "pages/flow.drawio"), "<mxfile><diagram/></mxfile>")
    with_fake_drawio_cli do
      result = convert("![Diagram](flow.drawio)\n")

      assert_empty result.problems
      refute_includes result.body, "drawio\""
      assert_includes result.body, '<ri:attachment ri:filename="flow.png" />'
      assert_equal %w[flow.drawio flow.png], result.attachments.keys.sort
    end
  end

  def test_diagram_references_to_pages_link_to_their_confluence_page_and_nothing_else
    File.write(File.join(@dir, "pages/linked.asd"), <<~ASD)
      component "a" { label "A"; resource "other" }
      component "b" { label "B"; resource "plain" }
      component "c" { label "C"; resource "Nope" }
      component "d" { label "D" }
    ASD
    svg = convert("![Linked](linked.asd)\n").attachments["linked.svg"].data

    assert_includes svg, '<a href="https://wiki.example.com/pages/viewpage.action?pageId=55" class="asd-link">'
    assert_equal 2, svg.scan('href="https://wiki.example.com/pages/viewpage.action?pageId=55"').length, "node and its label"
    refute_includes svg, "/kinds/", "no Archsight address leaks into Confluence"
    doc = REXML::Document.new(svg)
    broken = REXML::XPath.match(doc, "//*[contains(@class,'asd-broken-link') and starts-with(@id,'asd-node-')]").map { |n| n.attributes["id"] }

    assert_equal ["asd-node-c"], broken, "only the unknown reference is a broken node"
  end

  def test_the_wrapped_drawio_diagram_keeps_the_confluence_links
    File.write(File.join(@dir, "pages/linked.asd"), %(component "a" { label "A"; resource "other" }\n))
    with_fake_drawio_cli do
      xml = convert("![Linked](linked.asd)\n", drawio: true).attachments["linked"].data
      svg = Base64.decode64(xml[%r{image=data:image/svg\+xml,([A-Za-z0-9+/=]+)}, 1])

      assert_includes svg, 'href="https://wiki.example.com/pages/viewpage.action?pageId=55"'
    end
  end

  def test_a_diagram_that_does_not_render_is_a_problem
    result = convert("```asd\ncomponent {{{\n```\n")

    assert(result.problems.any? { |m| m.include?("diagram") })
  end

  def test_broken_images_are_problems_not_silently_dropped
    result = convert("![a](img/missing.png)\n\n![b](../../../etc/x.png)\n\n![c](notes.pdf)\n")

    assert_equal 3, result.problems.length
    assert_includes result.problems.join, "no such file"
    assert_includes result.problems.join, "leaves the resources directory"
  end

  def test_drawio_becomes_a_macro_with_the_diagram_and_a_preview_attached
    File.write(File.join(@dir, "pages/flow.drawio"), "<mxfile><diagram/></mxfile>")
    result = nil
    with_fake_drawio_cli { result = convert("![Diagram](flow.drawio)\n", drawio: true) }
    well_formed!(result.body)

    assert_empty result.problems
    assert_includes result.body, 'ac:name="drawio"'
    assert_includes result.body, '<ac:parameter ac:name="diagramName">flow</ac:parameter>'
    refute_includes result.body, "<p><ac:structured-macro ac:name=\"drawio\""
    assert_equal %w[flow flow.png], result.attachments.keys.sort
    assert_equal "PNGDATA", result.attachments["flow.png"].data
  ensure
    ENV.delete("ARCHSIGHT_DRAWIO_CLI")
  end

  def test_drawio_without_the_cli_is_reported
    File.write(File.join(@dir, "pages/flow.drawio"), "<mxfile><diagram/></mxfile>")
    ENV["ARCHSIGHT_DRAWIO_CLI"] = File.join(@dir, "does-not-exist")

    assert_includes convert("![Diagram](flow.drawio)\n").problems.join, "draw.io CLI"
  ensure
    ENV.delete("ARCHSIGHT_DRAWIO_CLI")
  end

  def test_macros_become_confluence_macros_also_in_tables_and_never_in_code
    result = convert("Now {status:green Done} {emoticon:2705 check mark button}\n\n| A | B |\n|---|---|\n| {status:red R&D} | `{status:red x}` |\n")
    well_formed!(result.body)

    assert_includes result.body, %(<ac:parameter ac:name="colour">Green</ac:parameter><ac:parameter ac:name="title">Done</ac:parameter>)
    assert_includes result.body, %(<ac:emoticon ac:emoji-id="2705" ac:name="check mark button")
    assert_includes result.body, %(<td><ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Red</ac:parameter><ac:parameter ac:name="title">R&amp;D</ac:parameter>)
    assert_includes result.body, "<code>{status:red x}</code>"
  end

  ALL_MACROS = <<~MD
    # Heading with {status:grey NEW}

    Text {status:yellow WIP} {emoticon:2705 check mark button} {emoticon:minus} {jira:PROJ-1} and `{status:red code}`.

    | A | B |
    |---|---|
    | {status:green OK} | {emoticon:274c cross mark} {jira:PROJ-2} |

    - item {status:blue INFO}
    - item {jira:PROJ-3}

    {children}

    {children:all sort=title reverse}

    {pagetree}

    A link [with {jira:PROJ-4} inside](https://example.com/x) and [a {status:red X} lozenge](https://example.com/y).
  MD

  def test_every_macro_in_every_position_gives_well_formed_storage_xml
    result = convert(ALL_MACROS)
    well_formed!(result.body)

    assert_operator result.body.scan('<ac:structured-macro ac:name="status">').length, :>=, 5
    assert_includes result.body, "<h1>Heading with <ac:structured-macro ac:name=\"status\">"
    assert_includes result.body, '<ac:emoticon ac:name="minus"/>'
    assert_includes result.body, '<ac:emoticon ac:emoji-id="2705" ac:name="check mark button"'
    assert_includes result.body, "<code>{status:red code}</code>"
    assert_includes result.body, '<td><ac:structured-macro ac:name="status">'
    assert_includes result.body, '<ac:structured-macro ac:name="children"></ac:structured-macro>'
    assert_includes result.body, '<ac:parameter ac:name="root"><ac:link /></ac:parameter>'
    assert_empty result.problems
  end

  def test_a_jira_macro_inside_a_link_is_plain_text_so_the_link_does_not_nest
    body = convert(ALL_MACROS).body

    assert_includes body, '<a href="https://example.com/x">with PROJ-4 inside</a>'
    assert_includes body, '<a href="https://example.com/y">a <ac:structured-macro ac:name="status">'
  end
end
