#!/usr/bin/env ruby
# frozen_string_literal: true

# Support running from source (development) and as installed gem
lib_path = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib_path) if File.directory?(lib_path)

require "archsight"
require "archsight/cli"

Archsight::CLI.start(ARGV)
