# frozen_string_literal: true

require_relative "base"

class Archsight::MCP::ExecuteAnalysisTool < FastMcp::Tool
  tool_name "execute_analysis"

  description <<~DESC.gsub("\n", " ").strip
    Discover and execute Analysis resources that validate architecture data and produce reports.

    TWO MODES OF OPERATION:

    1. LIST MODE (no name): Returns all available Analysis resources with name, description,
       handler, and timeout. Use this to discover what analyses exist before running them.

    2. EXECUTE MODE (name provided): Runs the specified Analysis script in a sandboxed environment
       and returns the results as markdown. The output includes structured findings like tables,
       lists, warnings, and errors generated by the script.
  DESC

  arguments do
    optional(:name).filled(:string).description(
      "Analysis name to execute (e.g., 'Analysis:Service:TeamOwnership'). " \
      "Omit to list all available analyses."
    )
    optional(:verbose).filled(:bool).description(
      "When true, tables and lists in output are not truncated. Default: false."
    )
  end

  def call(name: nil, verbose: false)
    if name.nil?
      list_analyses
    else
      execute_analysis(name, verbose: verbose)
    end
  rescue StandardError => e
    error_response(e.message)
  end

  private

  def list_analyses
    db = Archsight::MCP.db
    analyses = db.instances_by_kind("Analysis").values

    resources = analyses.map do |analysis|
      {
        name: analysis.name,
        description: analysis.annotations["analysis/description"] || analysis.annotations["architecture/description"],
        handler: analysis.annotations["analysis/handler"] || "ruby",
        timeout: analysis.annotations["analysis/timeout"] || "30s"
      }
    end

    JSON.pretty_generate(
      total: resources.size,
      analyses: resources
    )
  end

  def execute_analysis(name, verbose: false)
    require "archsight/analysis"

    db = Archsight::MCP.db
    analysis = db.instance_by_kind("Analysis", name)
    return error_response("Analysis not found: #{name}") unless analysis

    executor = Archsight::Analysis::Executor.new(db)
    result = executor.execute(analysis)

    if result.success?
      JSON.pretty_generate(
        name: result.name,
        success: true,
        duration: result.duration,
        output: result.to_markdown(verbose: verbose),
        has_findings: result.has_findings?,
        warning_count: result.warning_count,
        error_count: result.error_count
      )
    else
      response = {
        name: result.name,
        success: false,
        error: result.error
      }
      partial = result.to_markdown(verbose: verbose)
      response[:partial_output] = partial unless partial.empty?
      JSON.pretty_generate(response)
    end
  end

  def error_response(message)
    JSON.pretty_generate(
      error: "Error",
      message: message
    )
  end
end
