# frozen_string_literal: true

require "erb"
require "uri"
require "digest"
require "kramdown"
require "kramdown-parser-gfm"
require_relative "../../assets"
require_relative "../../diagram"
require_relative "../../helpers/macros"
require_relative "diagram_links"
require_relative "drawio"
require_relative "page_url"
require_relative "rasterizer"

module Archsight
  module Export
    module Confluence
      # A file that belongs to the exported page and is uploaded as an attachment
      Attachment = Struct.new(:filename, :data, :content_type, keyword_init: true) do
        def sha = Digest::SHA256.hexdigest(data)
      end

      # What the markdown of a page becomes in Confluence: the body in storage format, the attachments it refers
      # to and the problems that make it unfit for export (a missing image, a diagram that does not render).
      Converted = Struct.new(:body, :attachments, :problems, keyword_init: true)

      # Markdown -> Confluence storage format (XHTML with ac: macros)
      class Storage
        # The kramdown converter: HTML, except for code, images and the placeholders of links and embeds
        class Converter < Kramdown::Converter::Html
          def convert_codeblock(elem, _indent)
            language = elem.options[:lang].to_s
            return @options[:storage].diagram(elem.value, nil) if language == "asd"

            @options[:storage].code(elem.value, language)
          end

          def convert_p(elem, indent)
            image = elem.children.reject { |c| c.type == :text && c.value.strip.empty? }
            if image.length == 1 && image.first.type == :img && (block = @options[:storage].block_image(image.first.attr))
              return "#{block}\n"
            end

            super
          end

          def convert_img(elem, _indent)
            @options[:storage].image(elem.attr["src"].to_s, elem.attr["alt"].to_s)
          end

          # A link to a page of Archsight becomes a link to its Confluence page, or just its text if it has none;
          # a macro whose output is a link of its own (Jira) is shown as plain text inside a link: no link in a link
          def convert_a(elem, indent)
            storage = @options[:storage]
            target = storage.link_target(elem.attr["href"].to_s)
            return inner(elem, indent) unless target

            elem.attr["href"] = target
            storage.in_link { super }
          end

          def convert_text(elem, indent)
            @options[:storage].restore(super)
          end
        end

        MXFILE = "application/vnd.jgraph.mxfile"

        BANNER = "This page is generated by Archsight from <code>%<source>s</code>. " \
                 "Changes made here are overwritten by the next export: edit the source instead."

        LANGUAGES = {
          "sh" => "bash", "shell" => "bash", "zsh" => "bash", "yml" => "yaml", "json" => "javascript", "js" => "javascript",
          "html" => "html/xml", "xml" => "html/xml", "c" => "cpp", "ts" => "javascript", "md" => "text", "markdown" => "text"
        }.freeze
        KNOWN_LANGUAGES = %w[actionscript3 applescript bash c# cpp css coldfusion delphi diff erlang groovy html/xml java javafx
                             javascript perl php text powershell python ruby scala sql vb yaml].freeze
        PLACEHOLDER = /ARCHSIGHT(LINK|EMBED)(\d+)X/
        CODE = /(^[ \t]*(?:```|~~~).*?^[ \t]*(?:```|~~~)[ \t]*$|`[^`\n]*`)/m

        # @param page_name [String] used to name generated attachments
        # @param source [String] the markdown file, shown in the banner
        # @param base_dir [String] directory of the markdown file relative to the resources directory
        # @param resources_dir [String]
        # @param wiki [Archsight::Helpers::WikiLinks] resolves [[Targets]]
        # @param page_id [String, nil] id of the Confluence page, for the draw.io macro
        # @param base [String, nil] Confluence base URL, for the draw.io macro
        # @param database [Archsight::Database, nil] lets macros that name pages (pagetree) find them
        # @param diagram_links [#call, nil] resolves a diagram's `resource` references (DiagramLinks); none leaves them inert
        # @param drawio [Boolean] the Confluence has the draw.io app: diagrams go in as draw.io macros, else as images
        def initialize(page_name:, source:, base_dir:, resources_dir:, wiki:, page_id: nil, base: nil, drawio: false, diagram_links: nil, database: nil)
          @database = database
          @page_name = page_name
          @source = source
          @base_dir = base_dir
          @resources_dir = resources_dir
          @wiki = wiki
          @diagram_links = diagram_links
          @page_id = page_id
          @base = base
          @drawio = drawio
          @attachments = {}
          @problems = []
          @placeholders = []
          @diagrams = 0
        end

        # @param markdown [String] body of the page
        # @param toc [Boolean] add a table of contents
        # @param header [String] storage format put between the banner and the body (the page properties)
        # @return [Converted]
        def convert(markdown, toc: false, header: "")
          document = Kramdown::Document.new(protect(markdown), input: "GFM", auto_ids: false, entity_output: :as_char, smart_quotes: %w[apos apos quot quot])
          html, = Converter.convert(document.root, document.options.merge(storage: self))
          body = banner + header + (toc ? %(<ac:structured-macro ac:name="toc" />\n) : "") + html
          Converted.new(body: body, attachments: @attachments, problems: @problems)
        end

        # ---- called by the converter

        def code(source, language)
          language = LANGUAGES.fetch(language, language)
          language = "text" unless KNOWN_LANGUAGES.include?(language)
          %(<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">#{language}</ac:parameter>) +
            %(<ac:plain-text-body><![CDATA[#{source.chomp.gsub("]]>", "]]]]><![CDATA[>")}]]></ac:plain-text-body></ac:structured-macro>\n)
        end

        # A diagram from asd source (fenced block, .asd file) as block XML
        def diagram(source, stem)
          stem ||= "#{@page_name}-diagram-#{@diagrams += 1}"
          figure(Archsight::Diagram.render(source, resolver: @diagram_links), stem)
        rescue Archsight::Diagram::Error => e
          problem("diagram #{stem}: #{e.message}")
          ""
        end

        # An image that must not sit inside a paragraph (a diagram), nil for ordinary images
        def block_image(attr)
          path = asset_path(attr["src"].to_s)
          return nil unless path && diagram_file?(path)

          diagram_file(path)
        end

        def image(src, alt)
          return %(<ac:image ac:alt="#{h(alt)}"><ri:url ri:value="#{h(src)}" /></ac:image>) if Assets.external?(src)

          path = asset_path(src)
          return "" unless path
          return diagram_file(path).delete_prefix("<p>").delete_suffix("</p>\n") if diagram_file?(path)

          name = attach(Attachment.new(filename: File.basename(path), data: File.binread(file_of(path)), content_type: Assets.content_type(path)))
          %(<ac:image ac:alt="#{h(alt)}"><ri:attachment ri:filename="#{h(name)}" /></ac:image>)
        end

        def restore(text)
          text.gsub(PLACEHOLDER) do
            xml, plain = @placeholders.fetch(Regexp.last_match(2).to_i)
            @in_link && plain ? plain : xml
          end
        end

        # Where a markdown link leads in Confluence. The links of a page point into Archsight (`/pages/<name>`,
        # `/kinds/...`), which does not exist there: a page that has a Confluence page is linked to it, any other
        # Archsight path is not a link.
        # @return [String, nil] the href to use, nil for the text only
        def link_target(href)
          return href unless href.start_with?("/") && !href.start_with?("//")

          page = archsight_page(href)
          page && confluence_url(page)
        end

        # Runs the block for the content of a link
        def in_link
          previous = @in_link
          @in_link = true
          yield
        ensure
          @in_link = previous
        end

        private

        def banner
          %(<ac:structured-macro ac:name="info"><ac:rich-text-body><p>#{format(BANNER, source: h(@source))}</p></ac:rich-text-body></ac:structured-macro>\n)
        end

        # {macros}, [[Target|label]] and ![[View/Name]] become placeholders before kramdown sees them (it would split the
        # brackets), except in code.
        def protect(markdown)
          markdown.split(CODE).each_with_index.map { |part, i| i.odd? ? part : protect_text(part) }.join
        end

        def protect_text(text)
          text = Archsight::Helpers::Macros.replace(text) do |macro, value|
            xml = macro.confluence(value, Archsight::Helpers::Macros::Context.new(@database, nil))
            xml && placeholder("LINK", xml, plain: (macro.plain(value) if macro.respond_to?(:plain)))
          end
          text = text.gsub(/!\[\[([^\]|]+)\]\]/) { placeholder("EMBED", embed_note(Regexp.last_match(1).strip)) }
          text.gsub(Archsight::Helpers::WikiLinks::PATTERN) do
            placeholder("LINK", wiki_link(Regexp.last_match(1).strip, Regexp.last_match(2)&.strip))
          end
        end

        def placeholder(kind, xml, plain: nil)
          @placeholders << [xml, plain]
          "ARCHSIGHT#{kind}#{@placeholders.length - 1}X"
        end

        def embed_note(reference)
          "<em>#{h(reference)} (live content, shown in Archsight only)</em>"
        end

        # The page an Archsight path (`/pages/<name>`, `/kinds/Page/instances/<name>`, optionally with #anchor or ?query) shows
        def archsight_page(href)
          path = href.split(/[#?]/, 2).first.to_s
          name = path[%r{\A/pages/(.+)\z}, 1] || path[%r{\A/kinds/Page/instances/([^/]+)\z}, 1]
          name && @wiki.page_for(URI.decode_uri_component(name))
        rescue ArgumentError
          nil
        end

        def wiki_link(target, label)
          page = @wiki.page_for(target)
          text = label || page&.title || target
          url = page && confluence_url(page)
          url ? %(<a href="#{h(url)}">#{h(text)}</a>) : h(text)
        end

        def confluence_url(page) = DiagramLinks.confluence_url(page)

        # The normalized asset path of an image reference, nil (and a problem noted) if it cannot be exported
        def asset_path(src)
          return nil if Assets.external?(src)

          path = Assets.resolve_reference(src, @base_dir)
          reason = path ? Assets.problem(path, resources_dir: @resources_dir) : :outside
          problem("#{src}: #{{ outside: "leaves the resources directory", type: "file type is not served", missing: "no such file" }[reason]}") if reason
          reason ? nil : path
        end

        def file_of(path) = Assets.file_for(path, resources_dir: @resources_dir)

        # Files that are diagrams: draw.io and asd always, svg only where draw.io shows them
        def diagram_file?(path)
          Assets.drawio?(path) || Assets.asd?(path) || (@drawio && File.extname(path).casecmp?(".svg"))
        end

        def diagram_file(path)
          text = File.read(file_of(path), encoding: "UTF-8")
          stem = File.basename(path, ".*")
          if Assets.drawio?(path) then drawio_file(text, stem)
          elsif Assets.asd?(path) then diagram(text, stem)
          else figure(text, stem)
          end
        end

        # An SVG picture as block XML: a draw.io macro holding it, or an image
        def figure(svg, stem)
          return svg_macro(svg, stem) if @drawio

          attach(Attachment.new(filename: "#{stem}.svg", data: svg, content_type: "image/svg+xml"))
          png = Rasterizer.svg_to_png(svg)
          return image_block("#{stem}.svg") unless png

          image_block(attach(Attachment.new(filename: "#{stem}.png", data: png, content_type: "image/png")))
        end

        def svg_macro(svg, stem)
          xml = Drawio.wrap_svg(svg, stem)
          png = Rasterizer.svg_to_png(svg) || Rasterizer.drawio_to_png(xml)
          return no_preview(stem, "rsvg-convert or the draw.io CLI") unless png

          Drawio.macro(attach_diagram(stem, xml, png))
        end

        def drawio_file(xml, stem)
          png = Rasterizer.drawio_to_png(xml)
          return no_preview(stem, "the draw.io CLI (`drawio`, or ARCHSIGHT_DRAWIO_CLI)") unless png
          return Drawio.macro(attach_diagram(stem, xml, png)) if @drawio

          attach(Attachment.new(filename: "#{stem}.drawio", data: xml, content_type: MXFILE))
          image_block(attach(Attachment.new(filename: "#{stem}.png", data: png, content_type: "image/png")))
        end

        def no_preview(stem, tool)
          problem("#{stem}: #{tool} is needed to render the diagram")
          ""
        end

        def image_block(filename)
          %(<p><ac:image><ri:attachment ri:filename="#{h(filename)}" /></ac:image></p>\n)
        end

        # The diagram file of a draw.io macro and its `.png` preview, which must share the name
        # @return [String] the name the macro refers to
        def attach_diagram(stem, xml, png)
          sha = Digest::SHA256.hexdigest(xml)
          name = stem
          taken = ->(file, data) { @attachments.key?(file) && @attachments[file].data != data }
          name = "#{stem}-#{sha[0, 8]}" if taken.call(stem, xml) || taken.call("#{stem}.png", png)
          @attachments[name] = Attachment.new(filename: name, data: xml, content_type: MXFILE)
          @attachments["#{name}.png"] = Attachment.new(filename: "#{name}.png", data: png, content_type: "image/png")
          name
        end

        # @return [String] the filename under which the attachment is uploaded
        def attach(attachment)
          existing = @attachments[attachment.filename]
          return attachment.filename if existing && existing.sha == attachment.sha

          attachment.filename = "#{File.basename(attachment.filename, ".*")}-#{attachment.sha[0, 8]}#{File.extname(attachment.filename)}" if existing
          @attachments[attachment.filename] = attachment
          attachment.filename
        end

        def problem(message)
          @problems << message unless @problems.include?(message)
        end

        def h(text) = ERB::Util.html_escape(text)
      end
    end
  end
end
