{{- if and .Values.restart.enabled .Values.restart.token (not .Values.restart.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archsight.fullname" . }}-restart-token
  labels:
    {{- include "archsight.labels" . | nindent 4 }}
type: Opaque
data:
  restart-token: {{ .Values.restart.token | b64enc | quote }}
{{- end }}
